FROM 192.168.1.113/zhangpc/node_alpine_lts:4.4.7

RUN mkdir -p /opt/nodejs && mkdir -p ~/.ssh
COPY package.json /opt/nodejs
WORKDIR /opt/nodejs

RUN npm install npm -g --registry=https://registry.npm.taobao.org && \
    npm install --registry=https://registry.npm.taobao.org && \
    rm -f package.json && \
    npm uninstall -g npm && \
    rm -rf /tmp/* && \
    rm -rf /root/.npm
