apiVersion: v1beta1
id: mysql
desiredState:
  manifest:
    version: v1beta1
    id: mysql
    containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            # change this
            value: tenxcloud
        cpu: 100
        ports:
          - containerPort: 3306
labels:
  name: mysql
kind: Pod