apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: carrot
type: Opaque
data:
  # base64
  tenx-db-name: dGVueGNsb3Vk
  tenx-db-username: dGVueGNsb3Vk
  tenx-db-password: dGVueGNsb3Vk
  tenx-db-host: MTkyLjE2OC4xLjg3
  tenx-db-port: MzMwNg==